"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { Beaker, BookOpen, Bot, Newspaper, Search } from "lucide-react";
import { getExperiments, getKnowledgeItems, getNews, getTools } from "@/lib/data";

type Result={id:string;title:string;text:string;type:string;href:string;icon:typeof Bot};
export function SearchView(){const [query,setQuery]=useState(""),[all,setAll]=useState<Result[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{setQuery(new URLSearchParams(window.location.search).get("q")||"");Promise.all([getTools(),getNews(),getExperiments(),getKnowledgeItems()]).then(([tools,news,experiments,knowledge])=>setAll([...tools.map(x=>({id:x.id,title:x.name,text:x.description,type:"Инструмент",href:"/tools",icon:Bot})),...news.map(x=>({id:x.id,title:x.title,text:x.summary,type:"Новина",href:"/news",icon:Newspaper})),...experiments.map(x=>({id:x.id,title:x.name,text:`${x.description} ${x.result}`,type:"Експеримент",href:"/experiments",icon:Beaker})),...knowledge.map(x=>({id:x.id,title:x.title,text:`${x.description} ${x.tags.join(" ")}`,type:"Библиотека",href:"/library",icon:BookOpen}))])).finally(()=>setLoading(false))},[]);const results=useMemo(()=>{const q=query.trim().toLowerCase();return q?all.filter(item=>`${item.title} ${item.text} ${item.type}`.toLowerCase().includes(q)):[]},[all,query]);return <div><h1 className="text-3xl font-semibold">Общо търсене</h1><p className="mt-2 text-xs text-[#767869]">Търсете едновременно във всички модули.</p><div className="relative mt-6"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9a9b8d]" size={16}/><input autoFocus className="field py-3 pl-11" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Напишете ключова дума..."/></div><div className="mt-5 panel overflow-hidden">{loading?<div className="h-64 animate-pulse"/>:query&&!results.length?<div className="p-12 text-center text-sm text-[#767869]">Няма намерени резултати.</div>:results.map(item=>{const Icon=item.icon;return <Link href={item.href} key={`${item.type}-${item.id}`} className="flex items-center gap-4 border-b border-[#efeee4] p-4 last:border-0 hover:bg-[#f5f4ea]"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#e9edda] text-[#52621c]"><Icon size={15}/></span><div className="min-w-0"><p className="truncate text-xs font-semibold">{item.title}</p><p className="mt-1 line-clamp-1 text-[10px] text-[#767869]">{item.text}</p></div><span className="ml-auto text-[8px] uppercase text-[#9a9b8d]">{item.type}</span></Link>})}</div></div>}

